##### setup #####

library(targets)
source("R/functions.R")
tar_option_set(packages = c("tidyverse", "scLANE", "glm2", "scRNAseq", "parallel", "geeM", "SingleCellExperiment",
                            "scaffold", "pryr", "bigstatsr", "doParallel", "foreach", "tidyr", "slingshot", "igraph",
                            "MASS", "stats", "gamlss", "broom", "mgcv", "mvabund", "scran", "scater", "S4Vectors"),
               garbage_collection = TRUE)

##### targets #####

list(
  # prep data
  tar_target(lung_data_raw, scRNAseq::ZilionisLungData(which = "human")),
  tar_target(lung_data_clean, lung_data_raw[, lung_data_raw$Used]),
  # simulate datasets with 100 cells
  tar_target(lung_sim_DEG_01_CELLS_100, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.01, n.cells = 100)),
  tar_target(lung_sim_DEG_05_CELLS_100, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.05, n.cells = 100)),
  tar_target(lung_sim_DEG_10_CELLS_100, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.10, n.cells = 100)),
  tar_target(lung_sim_DEG_20_CELLS_100, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.20, n.cells = 100)),
  # simulate datasets with 500 cells
  tar_target(lung_sim_DEG_01_CELLS_500, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.01, n.cells = 500)),
  tar_target(lung_sim_DEG_05_CELLS_500, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.05, n.cells = 500)),
  tar_target(lung_sim_DEG_10_CELLS_500, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.10, n.cells = 500)),
  tar_target(lung_sim_DEG_20_CELLS_500, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.20, n.cells = 500)),
  # simulate datasets with 1,000 cells
  tar_target(lung_sim_DEG_01_CELLS_1000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.01, n.cells = 1000)),
  tar_target(lung_sim_DEG_05_CELLS_1000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.05, n.cells = 1000)),
  tar_target(lung_sim_DEG_10_CELLS_1000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.10, n.cells = 1000)),
  tar_target(lung_sim_DEG_20_CELLS_1000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.20, n.cells = 1000)),
  # simulate datasets with 5,000 cells
  tar_target(lung_sim_DEG_01_CELLS_5000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.01, n.cells = 5000)),
  tar_target(lung_sim_DEG_05_CELLS_5000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.05, n.cells = 5000)),
  tar_target(lung_sim_DEG_10_CELLS_5000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.10, n.cells = 5000)),
  tar_target(lung_sim_DEG_20_CELLS_5000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.20, n.cells = 5000)),
  # simulate datasets with 10,000 cells
  tar_target(lung_sim_DEG_01_CELLS_10000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.01, n.cells = 10000)),
  tar_target(lung_sim_DEG_05_CELLS_10000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.05, n.cells = 10000)),
  tar_target(lung_sim_DEG_10_CELLS_10000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.10, n.cells = 10000)),
  tar_target(lung_sim_DEG_20_CELLS_10000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.20, n.cells = 10000)),
  # simulate datasets with 30,000 cells
  tar_target(lung_sim_DEG_01_CELLS_30000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.01, n.cells = 30000)),
  tar_target(lung_sim_DEG_05_CELLS_30000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.05, n.cells = 30000)),
  tar_target(lung_sim_DEG_10_CELLS_30000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.10, n.cells = 30000)),
  tar_target(lung_sim_DEG_20_CELLS_30000, simulate_scaffold(ref.dataset = lung_data_clean, perc.dyn.genes = 0.20, n.cells = 30000)),
  # run scLANE for 100 cell datasets
  tar_target(scLANE_res_DEG_01_CELLS_100, run_scLANE(sim.data = lung_sim_DEG_01_CELLS_100,
                                                     n.iter = 3,
                                                     param.list = list(Prop_Dyn_Genes = 0.01, Cells = 100),
                                                     n.cores = 4)),
  tar_target(scLANE_res_DEG_05_CELLS_100, run_scLANE(sim.data = lung_sim_DEG_05_CELLS_100,
                                                     n.iter = 3,
                                                     param.list = list(Prop_Dyn_Genes = 0.05, Cells = 100),
                                                     n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_100, run_scLANE(sim.data = lung_sim_DEG_10_CELLS_100,
                                                     n.iter = 3,
                                                     param.list = list(Prop_Dyn_Genes = 0.10, Cells = 100),
                                                     n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_100, run_scLANE(sim.data = lung_sim_DEG_20_CELLS_100,
                                                     n.iter = 3,
                                                     param.list = list(Prop_Dyn_Genes = 0.20, Cells = 100),
                                                     n.cores = 4)),
  # run scLANE for 500 cell datasets
  tar_target(scLANE_res_DEG_01_CELLS_500, run_scLANE(sim.data = lung_sim_DEG_01_CELLS_500,
                                                     n.iter = 3,
                                                     param.list = list(Prop_Dyn_Genes = 0.01, Cells = 500),
                                                     n.cores = 4)),
  tar_target(scLANE_res_DEG_05_CELLS_500, run_scLANE(sim.data = lung_sim_DEG_05_CELLS_500,
                                                     n.iter = 3,
                                                     param.list = list(Prop_Dyn_Genes = 0.05, Cells = 500),
                                                     n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_500, run_scLANE(sim.data = lung_sim_DEG_10_CELLS_500,
                                                     n.iter = 3,
                                                     param.list = list(Prop_Dyn_Genes = 0.10, Cells = 500),
                                                     n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_500, run_scLANE(sim.data = lung_sim_DEG_20_CELLS_500,
                                                     n.iter = 3,
                                                     param.list = list(Prop_Dyn_Genes = 0.20, Cells = 500),
                                                     n.cores = 4)),
  # run scLANE for 1,000 cell datasets
  tar_target(scLANE_res_DEG_01_CELLS_1000, run_scLANE(sim.data = lung_sim_DEG_01_CELLS_1000,
                                                      n.iter = 3,
                                                      param.list = list(Prop_Dyn_Genes = 0.01, Cells = 1000),
                                                      n.cores = 4)),
  tar_target(scLANE_res_DEG_05_CELLS_1000, run_scLANE(sim.data = lung_sim_DEG_05_CELLS_1000,
                                                      n.iter = 3,
                                                      param.list = list(Prop_Dyn_Genes = 0.05, Cells = 1000),
                                                      n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_1000, run_scLANE(sim.data = lung_sim_DEG_10_CELLS_1000,
                                                      n.iter = 3,
                                                      param.list = list(Prop_Dyn_Genes = 0.10, Cells = 1000),
                                                      n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_1000, run_scLANE(sim.data = lung_sim_DEG_20_CELLS_1000,
                                                      n.iter = 3,
                                                      param.list = list(Prop_Dyn_Genes = 0.20, Cells = 1000),
                                                      n.cores = 4)),
  # run scLANE for 5,000 cell datasets
  tar_target(scLANE_res_DEG_01_CELLS_5000, run_scLANE(sim.data = lung_sim_DEG_01_CELLS_5000,
                                                      n.iter = 3,
                                                      param.list = list(Prop_Dyn_Genes = 0.01, Cells = 5000),
                                                      n.cores = 4)),
  tar_target(scLANE_res_DEG_05_CELLS_5000, run_scLANE(sim.data = lung_sim_DEG_05_CELLS_5000,
                                                      n.iter = 3,
                                                      param.list = list(Prop_Dyn_Genes = 0.05, Cells = 5000),
                                                      n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_5000, run_scLANE(sim.data = lung_sim_DEG_10_CELLS_5000,
                                                      n.iter = 3,
                                                      param.list = list(Prop_Dyn_Genes = 0.10, Cells = 5000),
                                                      n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_5000, run_scLANE(sim.data = lung_sim_DEG_20_CELLS_5000,
                                                      n.iter = 3,
                                                      param.list = list(Prop_Dyn_Genes = 0.20, Cells = 5000),
                                                      n.cores = 4)),
  # run scLANE for 10,000 cell datasets
  tar_target(scLANE_res_DEG_01_CELLS_10000, run_scLANE(sim.data = lung_sim_DEG_01_CELLS_10000,
                                                       n.iter = 3,
                                                       param.list = list(Prop_Dyn_Genes = 0.01, Cells = 10000),
                                                       n.cores = 4)),
  tar_target(scLANE_res_DEG_05_CELLS_10000, run_scLANE(sim.data = lung_sim_DEG_05_CELLS_10000,
                                                       n.iter = 3,
                                                       param.list = list(Prop_Dyn_Genes = 0.05, Cells = 10000),
                                                       n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_10000, run_scLANE(sim.data = lung_sim_DEG_10_CELLS_10000,
                                                       n.iter = 3,
                                                       param.list = list(Prop_Dyn_Genes = 0.10, Cells = 10000),
                                                       n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_10000, run_scLANE(sim.data = lung_sim_DEG_20_CELLS_10000,
                                                       n.iter = 3,
                                                       param.list = list(Prop_Dyn_Genes = 0.20, Cells = 10000),
                                                       n.cores = 4)),
  # run scLANE for 30,000 cell datasets
  tar_target(scLANE_res_DEG_01_CELLS_30000, run_scLANE(sim.data = lung_sim_DEG_01_CELLS_30000,
                                                       n.iter = 3,
                                                       param.list = list(Prop_Dyn_Genes = 0.01, Cells = 30000),
                                                       n.cores = 4)),
  tar_target(scLANE_res_DEG_05_CELLS_30000, run_scLANE(sim.data = lung_sim_DEG_05_CELLS_30000,
                                                       n.iter = 3,
                                                       param.list = list(Prop_Dyn_Genes = 0.05, Cells = 30000),
                                                       n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_30000, run_scLANE(sim.data = lung_sim_DEG_10_CELLS_30000,
                                                       n.iter = 3,
                                                       param.list = list(Prop_Dyn_Genes = 0.10, Cells = 30000),
                                                       n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_30000, run_scLANE(sim.data = lung_sim_DEG_20_CELLS_30000,
                                                       n.iter = 3,
                                                       param.list = list(Prop_Dyn_Genes = 0.20, Cells = 30000),
                                                       n.cores = 4))
)
