##### setup #####

library(future)
library(targets)
library(tarchetypes)
library(future.callr)

plan(callr)

source("R/functions.R")

tar_option_set(packages = c("tidyverse", "scLANE", "glm2", "scRNAseq", "parallel", "geeM", "SingleCellExperiment", "quarto", 
                            "scaffold", "pryr", "bigstatsr", "doParallel", "foreach", "tidyr", "slingshot", "igraph",
                            "MASS", "stats", "gamlss", "broom", "mgcv", "mvabund", "scran", "scater", "S4Vectors", "geeM"),
               garbage_collection = TRUE)

##### targets #####

list(
  ###### REFERENCE DATA #####
  
  tar_target(lung_data, scRNAseq::ZilionisLungData(which = "human", filter = TRUE)),
  tar_target(lung_data_clean, lung_data[rowSums(counts(lung_data)) != 0, ]), 
  
  ##### GLM SIMS #####
  
  # simulate 1-population datasets with 100 cells
  tar_target(lung_sim_DEG_01_CELLS_100, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                          perc.dyn.genes = 0.01, 
                                                          n.cells = 100)),
  tar_target(lung_sim_DEG_05_CELLS_100, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                          perc.dyn.genes = 0.05, 
                                                          n.cells = 100)),
  tar_target(lung_sim_DEG_10_CELLS_100, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                          perc.dyn.genes = 0.10, 
                                                          n.cells = 100)),
  tar_target(lung_sim_DEG_20_CELLS_100, simulate_scaffold(ref.dataset = lung_data_clean,
                                                          perc.dyn.genes = 0.20, 
                                                          n.cells = 100)),
  # simulate 1-population datasets with 500 cells
  tar_target(lung_sim_DEG_01_CELLS_500, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                          perc.dyn.genes = 0.01, 
                                                          n.cells = 500)),
  tar_target(lung_sim_DEG_05_CELLS_500, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                          perc.dyn.genes = 0.05, 
                                                          n.cells = 500)),
  tar_target(lung_sim_DEG_10_CELLS_500, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                          perc.dyn.genes = 0.10, 
                                                          n.cells = 500)),
  tar_target(lung_sim_DEG_20_CELLS_500, simulate_scaffold(ref.dataset = lung_data_clean,
                                                          perc.dyn.genes = 0.20, 
                                                          n.cells = 500)),
  # simulate 1-population datasets with 1,000 cells
  tar_target(lung_sim_DEG_01_CELLS_1000, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                           perc.dyn.genes = 0.01, 
                                                           n.cells = 1000)),
  tar_target(lung_sim_DEG_05_CELLS_1000, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                           perc.dyn.genes = 0.05, 
                                                           n.cells = 1000)),
  tar_target(lung_sim_DEG_10_CELLS_1000, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                           perc.dyn.genes = 0.10, 
                                                           n.cells = 1000)),
  tar_target(lung_sim_DEG_20_CELLS_1000, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                           perc.dyn.genes = 0.20, 
                                                           n.cells = 1000)),
  # simulate 1-population datasets with 5,000 cells
  tar_target(lung_sim_DEG_01_CELLS_5000, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                           perc.dyn.genes = 0.01, 
                                                           n.cells = 5000)),
  tar_target(lung_sim_DEG_05_CELLS_5000, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                           perc.dyn.genes = 0.05, 
                                                           n.cells = 5000)),
  tar_target(lung_sim_DEG_10_CELLS_5000, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                           perc.dyn.genes = 0.10, 
                                                           n.cells = 5000)),
  tar_target(lung_sim_DEG_20_CELLS_5000, simulate_scaffold(ref.dataset = lung_data_clean, 
                                                           perc.dyn.genes = 0.20, 
                                                           n.cells = 5000)),
  
  ##### GLM MODELS #####
  
  ### scLANE ###
  
  # run GLM scLANE for 100 cell datasets
  tar_target(scLANE_res_DEG_01_CELLS_100, run_scLANE_reduced(sim.data = lung_sim_DEG_01_CELLS_100, 
                                                             n.genes.sample = 3000, 
                                                             n.iter = 1,
                                                             param.list = list(Prop_Dyn_Genes = 0.01, Cells = 100),
                                                             n.cores = 4)),
  tar_target(scLANE_res_DEG_05_CELLS_100, run_scLANE_reduced(sim.data = lung_sim_DEG_05_CELLS_100, 
                                                             n.genes.sample = 4000, 
                                                             n.iter = 1,
                                                             param.list = list(Prop_Dyn_Genes = 0.05, Cells = 100),
                                                             n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_100, run_scLANE_reduced(sim.data = lung_sim_DEG_10_CELLS_100,
                                                             n.genes.sample = 2000, 
                                                             n.iter = 1,
                                                             param.list = list(Prop_Dyn_Genes = 0.10, Cells = 100),
                                                             n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_100, run_scLANE_reduced(sim.data = lung_sim_DEG_20_CELLS_100,
                                                             n.genes.sample = 3500, 
                                                             n.iter = 1,
                                                             param.list = list(Prop_Dyn_Genes = 0.20, Cells = 100),
                                                             n.cores = 4)),
  # run GLM scLANE for 500 cell datasets
  tar_target(scLANE_res_DEG_01_CELLS_500, run_scLANE_reduced(sim.data = lung_sim_DEG_01_CELLS_500,
                                                             n.genes.sample = 2700, 
                                                             n.iter = 1,
                                                             param.list = list(Prop_Dyn_Genes = 0.01, Cells = 500),
                                                             n.cores = 4)),
  tar_target(scLANE_res_DEG_05_CELLS_500, run_scLANE_reduced(sim.data = lung_sim_DEG_05_CELLS_500,
                                                             n.genes.sample = 3200, 
                                                             n.iter = 1,
                                                             param.list = list(Prop_Dyn_Genes = 0.05, Cells = 500),
                                                             n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_500, run_scLANE_reduced(sim.data = lung_sim_DEG_10_CELLS_500,
                                                             n.genes.sample = 4200, 
                                                             n.iter = 1,
                                                             param.list = list(Prop_Dyn_Genes = 0.10, Cells = 500),
                                                             n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_500, run_scLANE_reduced(sim.data = lung_sim_DEG_20_CELLS_500,
                                                             n.genes.sample = 1000, 
                                                             n.iter = 1,
                                                             param.list = list(Prop_Dyn_Genes = 0.20, Cells = 500),
                                                             n.cores = 4)),
  # run GLM scLANE for 1,000 cell datasets
  tar_target(scLANE_res_DEG_01_CELLS_1000, run_scLANE_reduced(sim.data = lung_sim_DEG_01_CELLS_1000,
                                                              n.genes.sample = 1100, 
                                                              n.iter = 1,
                                                              param.list = list(Prop_Dyn_Genes = 0.01, Cells = 1000),
                                                              n.cores = 4)),
  tar_target(scLANE_res_DEG_05_CELLS_1000, run_scLANE_reduced(sim.data = lung_sim_DEG_05_CELLS_1000,
                                                              n.genes.sample = 3600, 
                                                              n.iter = 1,
                                                              param.list = list(Prop_Dyn_Genes = 0.05, Cells = 1000),
                                                              n.cores = 8)),
  tar_target(scLANE_res_DEG_10_CELLS_1000, run_scLANE_reduced(sim.data = lung_sim_DEG_10_CELLS_1000,
                                                              n.genes.sample = 2700, 
                                                              n.iter = 1,
                                                              param.list = list(Prop_Dyn_Genes = 0.10, Cells = 1000),
                                                              n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_1000, run_scLANE_reduced(sim.data = lung_sim_DEG_20_CELLS_1000,
                                                              n.genes.sample = 1400, 
                                                              n.iter = 1,
                                                              param.list = list(Prop_Dyn_Genes = 0.20, Cells = 1000),
                                                              n.cores = 4)),
  # run GLM scLANE for 5,000 cell datasets
  tar_target(scLANE_res_DEG_01_CELLS_5000, run_scLANE_reduced(sim.data = lung_sim_DEG_01_CELLS_5000,
                                                              n.genes.sample = 3500, 
                                                              n.iter = 1,
                                                              param.list = list(Prop_Dyn_Genes = 0.01, Cells = 5000),
                                                              n.cores = 4)),
  tar_target(scLANE_res_DEG_05_CELLS_5000, run_scLANE_reduced(sim.data = lung_sim_DEG_05_CELLS_5000,
                                                              n.genes.sample = 1100, 
                                                              n.iter = 1,
                                                              param.list = list(Prop_Dyn_Genes = 0.05, Cells = 5000),
                                                              n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_5000, run_scLANE_reduced(sim.data = lung_sim_DEG_10_CELLS_5000,
                                                              n.genes.sample = 5000, 
                                                              n.iter = 1,
                                                              param.list = list(Prop_Dyn_Genes = 0.10, Cells = 5000),
                                                              n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_5000, run_scLANE_reduced(sim.data = lung_sim_DEG_20_CELLS_5000,
                                                              n.genes.sample = 2200, 
                                                              n.iter = 1,
                                                              param.list = list(Prop_Dyn_Genes = 0.20, Cells = 5000),
                                                              n.cores = 4)), 
  
  ### tradeSeq ###
  # run tradeSeq on 100 cell GLM sims 
  tar_target(tradeSeq_res_DEG_01_CELLS_100, run_tradeSeq_reduced(sim.data = lung_sim_DEG_01_CELLS_100, 
                                                                 n.genes.sample = 1600, 
                                                                 n.iter = 1, 
                                                                 param.list = list(Prop_Dyn_Gene = 0.01, Cells = 100), 
                                                                 n.cores = 4)),
  tar_target(tradeSeq_res_DEG_05_CELLS_100, run_tradeSeq_reduced(sim.data = lung_sim_DEG_05_CELLS_100, 
                                                                 n.genes.sample = 2500, 
                                                                 n.iter = 1, 
                                                                 param.list = list(Prop_Dyn_Gene = 0.05, Cells = 100), 
                                                                 n.cores = 4)),
  tar_target(tradeSeq_res_DEG_10_CELLS_100, run_tradeSeq_reduced(sim.data = lung_sim_DEG_10_CELLS_100, 
                                                                 n.genes.sample = 3300, 
                                                                 n.iter = 1, 
                                                                 param.list = list(Prop_Dyn_Gene = 0.10, Cells = 100), 
                                                                 n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_100, run_tradeSeq_reduced(sim.data = lung_sim_DEG_20_CELLS_100, 
                                                                 n.genes.sample = 1100, 
                                                                 n.iter = 1, 
                                                                 param.list = list(Prop_Dyn_Gene = 0.20, Cells = 100), 
                                                                 n.cores = 4)),
  # run tradeSeq on 500 cell GLM sims 
  tar_target(tradeSeq_res_DEG_01_CELLS_500, run_tradeSeq_reduced(sim.data = lung_sim_DEG_01_CELLS_500, 
                                                                 n.genes.sample = 3100, 
                                                                 n.iter = 1, 
                                                                 param.list = list(Prop_Dyn_Gene = 0.01, Cells = 500), 
                                                                 n.cores = 4)),
  tar_target(tradeSeq_res_DEG_05_CELLS_500, run_tradeSeq_reduced(sim.data = lung_sim_DEG_05_CELLS_500, 
                                                                 n.genes.sample = 2000, 
                                                                 n.iter = 1, 
                                                                 param.list = list(Prop_Dyn_Gene = 0.05, Cells = 500), 
                                                                 n.cores = 4)),
  tar_target(tradeSeq_res_DEG_10_CELLS_500, run_tradeSeq_reduced(sim.data = lung_sim_DEG_10_CELLS_500, 
                                                                 n.genes.sample = 2500, 
                                                                 n.iter = 1, 
                                                                 param.list = list(Prop_Dyn_Gene = 0.10, Cells = 500), 
                                                                 n.cores = 4)),
  
  tar_target(tradeSeq_res_DEG_20_CELLS_500, run_tradeSeq_reduced(sim.data = lung_sim_DEG_20_CELLS_500, 
                                                                 n.genes.sample = 4000, 
                                                                 n.iter = 1, 
                                                                 param.list = list(Prop_Dyn_Gene = 0.20, Cells = 500), 
                                                                 n.cores = 4)),
  # run tradeSeq on 1,000 cell GLM sims 
  tar_target(tradeSeq_res_DEG_01_CELLS_1000, run_tradeSeq_reduced(sim.data = lung_sim_DEG_01_CELLS_1000, 
                                                                  n.genes.sample = 2600, 
                                                                  n.iter = 1, 
                                                                  param.list = list(Prop_Dyn_Gene = 0.01, Cells = 1000), 
                                                                  n.cores = 4)),
  tar_target(tradeSeq_res_DEG_05_CELLS_1000, run_tradeSeq_reduced(sim.data = lung_sim_DEG_05_CELLS_1000, 
                                                                  n.genes.sample = 1600, 
                                                                  n.iter = 1, 
                                                                  param.list = list(Prop_Dyn_Gene = 0.05, Cells = 1000), 
                                                                  n.cores = 4)),
  tar_target(tradeSeq_res_DEG_10_CELLS_1000, run_tradeSeq_reduced(sim.data = lung_sim_DEG_10_CELLS_1000, 
                                                                  n.genes.sample = 2200, 
                                                                  n.iter = 1, 
                                                                  param.list = list(Prop_Dyn_Gene = 0.10, Cells = 1000), 
                                                                  n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_1000, run_tradeSeq_reduced(sim.data = lung_sim_DEG_20_CELLS_1000, 
                                                                  n.genes.sample = 2300, 
                                                                  n.iter = 1, 
                                                                  param.list = list(Prop_Dyn_Gene = 0.20, Cells = 1000), 
                                                                  n.cores = 4)),
  # run tradeSeq on 5,000 cell GLM sims 
  tar_target(tradeSeq_res_DEG_01_CELLS_5000, run_tradeSeq_reduced(sim.data = lung_sim_DEG_01_CELLS_5000, 
                                                                  n.genes.sample = 2000, 
                                                                  n.iter = 1, 
                                                                  param.list = list(Prop_Dyn_Gene = 0.20, Cells = 5000), 
                                                                  n.cores = 4)),
  tar_target(tradeSeq_res_DEG_05_CELLS_5000, run_tradeSeq_reduced(sim.data = lung_sim_DEG_05_CELLS_5000, 
                                                                  n.genes.sample = 3600, 
                                                                  n.iter = 1, 
                                                                  param.list = list(Prop_Dyn_Gene = 0.20, Cells = 5000), 
                                                                  n.cores = 4)),
  tar_target(tradeSeq_res_DEG_10_CELLS_5000, run_tradeSeq_reduced(sim.data = lung_sim_DEG_10_CELLS_5000, 
                                                                  n.genes.sample = 1500, 
                                                                  n.iter = 1, 
                                                                  param.list = list(Prop_Dyn_Gene = 0.20, Cells = 5000), 
                                                                  n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_5000, run_tradeSeq_reduced(sim.data = lung_sim_DEG_20_CELLS_5000, 
                                                                  n.genes.sample = 3500, 
                                                                  n.iter = 1, 
                                                                  param.list = list(Prop_Dyn_Gene = 0.20, Cells = 5000), 
                                                                  n.cores = 4)),
  
  ##### GEE SIMS #####
  
  # simulate 6-subject datasets with 100 cells
  tar_target(lung_sim_DEG_10_CELLS_100_balanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                       perc.dyn.genes = 0.1,
                                                                       n.cells = 100,
                                                                       perc.allocation = rep(1/6, 6),
                                                                       n.subjects = 6)),
  tar_target(lung_sim_DEG_20_CELLS_100_balanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                       perc.dyn.genes = 0.2,
                                                                       n.cells = 100,
                                                                       perc.allocation = rep(1/6, 6),
                                                                       n.subjects = 6)),
  tar_target(lung_sim_DEG_10_CELLS_100_unbalanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                         perc.dyn.genes = 0.1,
                                                                         n.cells = 100,
                                                                         perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                         n.subjects = 6)),
  tar_target(lung_sim_DEG_20_CELLS_100_unbalanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                         perc.dyn.genes = 0.2,
                                                                         n.cells = 100,
                                                                         perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                         n.subjects = 6)),
  # simulate 6-subject datasets with 250 cells
  tar_target(lung_sim_DEG_10_CELLS_250_balanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                       perc.dyn.genes = 0.1,
                                                                       n.cells = 250,
                                                                       perc.allocation = rep(1/6, 6),
                                                                       n.subjects = 6)),
  tar_target(lung_sim_DEG_20_CELLS_250_balanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                       perc.dyn.genes = 0.2,
                                                                       n.cells = 250,
                                                                       perc.allocation = rep(1/6, 6),
                                                                       n.subjects = 6)),
  tar_target(lung_sim_DEG_10_CELLS_250_unbalanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                         perc.dyn.genes = 0.1,
                                                                         n.cells = 250,
                                                                         perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                         n.subjects = 6)),
  tar_target(lung_sim_DEG_20_CELLS_250_unbalanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                         perc.dyn.genes = 0.2,
                                                                         n.cells = 250,
                                                                         perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                         n.subjects = 6)),
  # simulate 6-subject datasets with 1,000 cells
  tar_target(lung_sim_DEG_10_CELLS_1000_balanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                        perc.dyn.genes = 0.1,
                                                                        n.cells = 1000,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(lung_sim_DEG_20_CELLS_1000_balanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                        perc.dyn.genes = 0.2,
                                                                        n.cells = 1000,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(lung_sim_DEG_10_CELLS_1000_unbalanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                          perc.dyn.genes = 0.1,
                                                                          n.cells = 1000,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  tar_target(lung_sim_DEG_20_CELLS_1000_unbalanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                          perc.dyn.genes = 0.2,
                                                                          n.cells = 1000,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  # simulate 6-subject datasets with 5,000 cells
  tar_target(lung_sim_DEG_10_CELLS_5000_balanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                        perc.dyn.genes = 0.1,
                                                                        n.cells = 5000,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(lung_sim_DEG_20_CELLS_5000_balanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                        perc.dyn.genes = 0.2,
                                                                        n.cells = 5000,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(lung_sim_DEG_10_CELLS_5000_unbalanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                          perc.dyn.genes = 0.1,
                                                                          n.cells = 5000,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  tar_target(lung_sim_DEG_20_CELLS_5000_unbalanced, simulate_scaffold_GEE(ref.dataset = lung_data_clean,
                                                                          perc.dyn.genes = 0.2,
                                                                          n.cells = 5000,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  
  ##### GEE MODELS #####
  
  ### scLANE ###
  
  # run GEE scLANE for 100 cell datasets
  tar_target(scLANE_res_DEG_10_CELLS_100_balanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_100_balanced,
                                                                          n.genes.sample = 2000, 
                                                                          n.iter = 1,
                                                                          param.list = list(Prop_Dyn_Genes = 0.1, Cells = 100, Allocation = "balanced"),
                                                                          n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_100_balanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_100_balanced,
                                                                          n.genes.sample = 4000, 
                                                                          n.iter = 1,
                                                                          param.list = list(Prop_Dyn_Genes = 0.2, Cells = 100, Allocation = "balanced"),
                                                                          n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_100_unbalanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_100_unbalanced,
                                                                            n.genes.sample = 3100, 
                                                                            n.iter = 1,
                                                                            param.list = list(Prop_Dyn_Genes = 0.1, Cells = 100, Allocation = "unbalanced"),
                                                                            n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_100_unbalanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_100_unbalanced,
                                                                            n.genes.sample = 1400, 
                                                                            n.iter = 1,
                                                                            param.list = list(Prop_Dyn_Genes = 0.2, Cells = 100, Allocation = "unbalanced"),
                                                                            n.cores = 4)), 
  # run GEE scLANE for 250 cell datasets
  tar_target(scLANE_res_DEG_10_CELLS_250_balanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_250_balanced,
                                                                          n.genes.sample = 4600, 
                                                                          n.iter = 1,
                                                                          param.list = list(Prop_Dyn_Genes = 0.1, Cells = 250, Allocation = "balanced"),
                                                                          n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_250_balanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_250_balanced,
                                                                          n.genes.sample = 3500, 
                                                                          n.iter = 1,
                                                                          param.list = list(Prop_Dyn_Genes = 0.2, Cells = 250, Allocation = "balanced"),
                                                                          n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_250_unbalanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_250_unbalanced,
                                                                            n.genes.sample = 1800, 
                                                                            n.iter = 1,
                                                                            param.list = list(Prop_Dyn_Genes = 0.1, Cells = 250, Allocation = "unbalanced"),
                                                                            n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_250_unbalanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_250_unbalanced,
                                                                            n.genes.sample = 3400, 
                                                                            n.iter = 1,
                                                                            param.list = list(Prop_Dyn_Genes = 0.2, Cells = 250, Allocation = "unbalanced"),
                                                                            n.cores = 4)), 
  # run GEE scLANE for 1,000 cell datasets
  tar_target(scLANE_res_DEG_10_CELLS_1000_balanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_1000_balanced,
                                                                           n.genes.sample = 2300, 
                                                                           n.iter = 1,
                                                                           param.list = list(Prop_Dyn_Genes = 0.1, Cells = 1000, Allocation = "balanced"),
                                                                           n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_1000_balanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_1000_balanced,
                                                                           n.genes.sample = 1600, 
                                                                           n.iter = 1,
                                                                           param.list = list(Prop_Dyn_Genes = 0.2, Cells = 1000, Allocation = "balanced"),
                                                                           n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_1000_unbalanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_1000_unbalanced,
                                                                             n.genes.sample = 4000, 
                                                                             n.iter = 1,
                                                                             param.list = list(Prop_Dyn_Genes = 0.1, Cells = 1000, Allocation = "unbalanced"),
                                                                             n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_1000_unbalanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_1000_unbalanced,
                                                                             n.genes.sample = 2600, 
                                                                             n.iter = 1,
                                                                             param.list = list(Prop_Dyn_Genes = 0.2, Cells = 1000, Allocation = "unbalanced"),
                                                                             n.cores = 4)), 
  # run GEE scLANE for 5,000 cell datasets
  tar_target(scLANE_res_DEG_10_CELLS_5000_balanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_5000_balanced,
                                                                           n.genes.sample = 4100, 
                                                                           n.iter = 1,
                                                                           param.list = list(Prop_Dyn_Genes = 0.1, Cells = 5000, Allocation = "balanced"),
                                                                           n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_5000_balanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_5000_balanced,
                                                                           n.genes.sample = 1500, 
                                                                           n.iter = 1,
                                                                           param.list = list(Prop_Dyn_Genes = 0.2, Cells = 5000, Allocation = "balanced"),
                                                                           n.cores = 4)),
  tar_target(scLANE_res_DEG_10_CELLS_5000_unbalanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_5000_unbalanced,
                                                                             n.genes.sample = 1700, 
                                                                             n.iter = 1,
                                                                             param.list = list(Prop_Dyn_Genes = 0.1, Cells = 5000, Allocation = "unbalanced"),
                                                                             n.cores = 4)),
  tar_target(scLANE_res_DEG_20_CELLS_5000_unbalanced, run_scLANE_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_5000_unbalanced,
                                                                             n.genes.sample = 1900, 
                                                                             n.iter = 1,
                                                                             param.list = list(Prop_Dyn_Genes = 0.2, Cells = 5000, Allocation = "unbalanced"),
                                                                             n.cores = 4)), 
  
  ### tradeSeq ###
  
  # run tradeSeq on 100 cell GEE sims 
  tar_target(tradeSeq_res_DEG_10_CELLS_100_balanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_100_balanced,
                                                                              n.genes.sample = 2000, 
                                                                              n.iter = 1,
                                                                              param.list = list(Prop_Dyn_Genes = 0.1, Cells = 100, Allocation = "balanced"),
                                                                              n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_100_balanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_100_balanced,
                                                                              n.genes.sample = 1200, 
                                                                              n.iter = 1,
                                                                              param.list = list(Prop_Dyn_Genes = 0.2, Cells = 100, Allocation = "balanced"),
                                                                              n.cores = 4)),
  tar_target(tradeSeq_res_DEG_10_CELLS_100_unbalanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_100_unbalanced,
                                                                                n.genes.sample = 1800, 
                                                                                n.iter = 1,
                                                                                param.list = list(Prop_Dyn_Genes = 0.1, Cells = 100, Allocation = "unbalanced"),
                                                                                n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_100_unbalanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_100_unbalanced,
                                                                                n.genes.sample = 3100, 
                                                                                n.iter = 1,
                                                                                param.list = list(Prop_Dyn_Genes = 0.2, Cells = 100, Allocation = "unbalanced"),
                                                                                n.cores = 4)),
  # run tradeSeq on 250 cell GEE sims 
  tar_target(tradeSeq_res_DEG_10_CELLS_250_balanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_250_balanced,
                                                                              n.genes.sample = 3000, 
                                                                              n.iter = 1,
                                                                              param.list = list(Prop_Dyn_Genes = 0.1, Cells = 250, Allocation = "balanced"),
                                                                              n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_250_balanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_250_balanced,
                                                                              n.genes.sample = 2600, 
                                                                              n.iter = 1,
                                                                              param.list = list(Prop_Dyn_Genes = 0.2, Cells = 250, Allocation = "balanced"),
                                                                              n.cores = 4)),
  tar_target(tradeSeq_res_DEG_10_CELLS_250_unbalanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_250_unbalanced,
                                                                                n.genes.sample = 2200, 
                                                                                n.iter = 1,
                                                                                param.list = list(Prop_Dyn_Genes = 0.1, Cells = 250, Allocation = "unbalanced"),
                                                                                n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_250_unbalanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_250_unbalanced,
                                                                                n.genes.sample = 1500, 
                                                                                n.iter = 1,
                                                                                param.list = list(Prop_Dyn_Genes = 0.2, Cells = 250, Allocation = "unbalanced"),
                                                                                n.cores = 4)), 
  # run tradeSeq on 1,000 cell GEE sims 
  tar_target(tradeSeq_res_DEG_10_CELLS_1000_balanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_1000_balanced,
                                                                               n.genes.sample = 1400, 
                                                                               n.iter = 1,
                                                                               param.list = list(Prop_Dyn_Genes = 0.1, Cells = 1000, Allocation = "balanced"),
                                                                               n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_1000_balanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_1000_balanced,
                                                                               n.genes.sample = 2000, 
                                                                               n.iter = 1,
                                                                               param.list = list(Prop_Dyn_Genes = 0.2, Cells = 1000, Allocation = "balanced"),
                                                                               n.cores = 4)),
  tar_target(tradeSeq_res_DEG_10_CELLS_1000_unbalanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_1000_unbalanced,
                                                                                 n.genes.sample = 3100, 
                                                                                 n.iter = 1,
                                                                                 param.list = list(Prop_Dyn_Genes = 0.1, Cells = 1000, Allocation = "unbalanced"),
                                                                                 n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_1000_unbalanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_1000_unbalanced,
                                                                                 n.genes.sample = 1900, 
                                                                                 n.iter = 1,
                                                                                 param.list = list(Prop_Dyn_Genes = 0.2, Cells = 1000, Allocation = "unbalanced"),
                                                                                 n.cores = 4)), 
  # run tradeSeq on 5,000 cell GEE sims 
  tar_target(tradeSeq_res_DEG_10_CELLS_5000_balanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_5000_balanced,
                                                                               n.genes.sample = 2200, 
                                                                               n.iter = 1,
                                                                               param.list = list(Prop_Dyn_Genes = 0.1, Cells = 5000, Allocation = "balanced"),
                                                                               n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_5000_balanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_5000_balanced,
                                                                               n.genes.sample = 1100, 
                                                                               n.iter = 1,
                                                                               param.list = list(Prop_Dyn_Genes = 0.2, Cells = 5000, Allocation = "balanced"),
                                                                               n.cores = 4)),
  tar_target(tradeSeq_res_DEG_10_CELLS_5000_unbalanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_10_CELLS_5000_unbalanced,
                                                                                 n.genes.sample = 1800, 
                                                                                 n.iter = 1,
                                                                                 param.list = list(Prop_Dyn_Genes = 0.1, Cells = 5000, Allocation = "unbalanced"),
                                                                                 n.cores = 4)),
  tar_target(tradeSeq_res_DEG_20_CELLS_5000_unbalanced, run_tradeSeq_reduced_GEE(sim.data = lung_sim_DEG_20_CELLS_5000_unbalanced,
                                                                                 n.genes.sample = 2500, 
                                                                                 n.iter = 1,
                                                                                 param.list = list(Prop_Dyn_Genes = 0.2, Cells = 5000, Allocation = "unbalanced"),
                                                                                 n.cores = 4))
  
  ##### OUTPUT #####
  
  # tar_quarto(performance_report, "Simulation_Analysis.qmd", cue = tar_cue(mode = "never"))
)

