##### SETUP #####

library(future)
library(targets)
library(tarchetypes)
library(future.callr)

future::plan(future.callr::callr)
options(future.globals.maxSize = 100000 * 1024^2)  # 100GB max size -- necessary for loading in all sim datasets

source("./R/functions_simulation.R")

tar_option_set(packages = c("stats", 
                            "scran", 
                            "scater", 
                            "igraph", 
                            "Matrix", 
                            "scRNAseq", 
                            "scaffold", 
                            "S4Vectors", 
                            "tidyverse", 
                            "rmarkdown", 
                            "SummarizedExperiment", 
                            "SingleCellExperiment"), 
               error = "continue", 
               memory = "transient", 
               storage = "worker", 
               retrieval = "worker", 
               garbage_collection = TRUE, 
               format = "qs")

list(
  ##### BRAIN #####
  # reference data 
  tar_target(brain_data_clean, fetch_lamanno_brain_data()), 
  ### SINGLE-SUBJECT 
  # 100 cells
  tar_target(brain_sim_DEG_01_CELLS_100, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                 perc.dyn.genes = 0.01, 
                                                                 n.cells = 100)),
  tar_target(brain_sim_DEG_05_CELLS_100, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                 perc.dyn.genes = 0.05, 
                                                                 n.cells = 100)),
  tar_target(brain_sim_DEG_10_CELLS_100, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                 perc.dyn.genes = 0.10, 
                                                                 n.cells = 100)),
  tar_target(brain_sim_DEG_20_CELLS_100, simulate_single_subject(ref.dataset = brain_data_clean,
                                                                 perc.dyn.genes = 0.20, 
                                                                 n.cells = 100)),
  # 500 cells
  tar_target(brain_sim_DEG_01_CELLS_500, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                 perc.dyn.genes = 0.01, 
                                                                 n.cells = 500)),
  tar_target(brain_sim_DEG_05_CELLS_500, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                 perc.dyn.genes = 0.05, 
                                                                 n.cells = 500)),
  tar_target(brain_sim_DEG_10_CELLS_500, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                 perc.dyn.genes = 0.10, 
                                                                 n.cells = 500)),
  tar_target(brain_sim_DEG_20_CELLS_500, simulate_single_subject(ref.dataset = brain_data_clean,
                                                                 perc.dyn.genes = 0.20, 
                                                                 n.cells = 500)),
  # 1000 cells
  tar_target(brain_sim_DEG_01_CELLS_1000, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.01, 
                                                                  n.cells = 1000)),
  tar_target(brain_sim_DEG_05_CELLS_1000, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.05, 
                                                                  n.cells = 1000)),
  tar_target(brain_sim_DEG_10_CELLS_1000, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.10, 
                                                                  n.cells = 1000)),
  tar_target(brain_sim_DEG_20_CELLS_1000, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.20, 
                                                                  n.cells = 1000)),
  # 2500 cells
  tar_target(brain_sim_DEG_01_CELLS_2500, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.01, 
                                                                  n.cells = 2500)),
  tar_target(brain_sim_DEG_05_CELLS_2500, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.05, 
                                                                  n.cells = 2500)),
  tar_target(brain_sim_DEG_10_CELLS_2500, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.10, 
                                                                  n.cells = 2500)),
  tar_target(brain_sim_DEG_20_CELLS_2500, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.20, 
                                                                  n.cells = 2500)),
  # 5000 cells
  tar_target(brain_sim_DEG_01_CELLS_5000, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.01, 
                                                                  n.cells = 5000)),
  tar_target(brain_sim_DEG_05_CELLS_5000, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.05, 
                                                                  n.cells = 5000)),
  tar_target(brain_sim_DEG_10_CELLS_5000, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.10, 
                                                                  n.cells = 5000)),
  tar_target(brain_sim_DEG_20_CELLS_5000, simulate_single_subject(ref.dataset = brain_data_clean, 
                                                                  perc.dyn.genes = 0.20, 
                                                                  n.cells = 5000)), 
  ### MULTI-SUBJECT -- homogeneous
  # 100 cells
  tar_target(brain_sim_DEG_10_CELLS_100_balanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                         perc.dyn.genes = 0.1,
                                                                         n.cells = 100,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(brain_sim_DEG_20_CELLS_100_balanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                         perc.dyn.genes = 0.2,
                                                                         n.cells = 100,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(brain_sim_DEG_10_CELLS_100_unbalanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                           perc.dyn.genes = 0.1,
                                                                           n.cells = 100,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  tar_target(brain_sim_DEG_20_CELLS_100_unbalanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                           perc.dyn.genes = 0.2,
                                                                           n.cells = 100,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  # 500 cells
  tar_target(brain_sim_DEG_10_CELLS_500_balanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                         perc.dyn.genes = 0.1,
                                                                         n.cells = 500,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(brain_sim_DEG_20_CELLS_500_balanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                         perc.dyn.genes = 0.2,
                                                                         n.cells = 500,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(brain_sim_DEG_10_CELLS_500_unbalanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                           perc.dyn.genes = 0.1,
                                                                           n.cells = 500,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  tar_target(brain_sim_DEG_20_CELLS_500_unbalanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                           perc.dyn.genes = 0.2,
                                                                           n.cells = 500,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  # 1000 cells
  tar_target(brain_sim_DEG_10_CELLS_1000_balanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                          perc.dyn.genes = 0.1,
                                                                          n.cells = 1000,
                                                                          perc.allocation = rep(1/6, 6),
                                                                          n.subjects = 6)),
  tar_target(brain_sim_DEG_20_CELLS_1000_balanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                          perc.dyn.genes = 0.2,
                                                                          n.cells = 1000,
                                                                          perc.allocation = rep(1/6, 6),
                                                                          n.subjects = 6)),
  tar_target(brain_sim_DEG_10_CELLS_1000_unbalanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                            perc.dyn.genes = 0.1,
                                                                            n.cells = 1000,
                                                                            perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                            n.subjects = 6)),
  tar_target(brain_sim_DEG_20_CELLS_1000_unbalanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                            perc.dyn.genes = 0.2,
                                                                            n.cells = 1000,
                                                                            perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                            n.subjects = 6)),
  # 2500 cells
  tar_target(brain_sim_DEG_10_CELLS_2500_balanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                          perc.dyn.genes = 0.1,
                                                                          n.cells = 2500,
                                                                          perc.allocation = rep(1/6, 6),
                                                                          n.subjects = 6)),
  tar_target(brain_sim_DEG_20_CELLS_2500_balanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                          perc.dyn.genes = 0.2,
                                                                          n.cells = 2500,
                                                                          perc.allocation = rep(1/6, 6),
                                                                          n.subjects = 6)),
  tar_target(brain_sim_DEG_10_CELLS_2500_unbalanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                            perc.dyn.genes = 0.1,
                                                                            n.cells = 2500,
                                                                            perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                            n.subjects = 6)),
  tar_target(brain_sim_DEG_20_CELLS_2500_unbalanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                            perc.dyn.genes = 0.2,
                                                                            n.cells = 2500,
                                                                            perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                            n.subjects = 6)),
  # 5000 cells
  tar_target(brain_sim_DEG_10_CELLS_5000_balanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                          perc.dyn.genes = 0.1,
                                                                          n.cells = 5000,
                                                                          perc.allocation = rep(1/6, 6),
                                                                          n.subjects = 6)),
  tar_target(brain_sim_DEG_20_CELLS_5000_balanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                          perc.dyn.genes = 0.2,
                                                                          n.cells = 5000,
                                                                          perc.allocation = rep(1/6, 6),
                                                                          n.subjects = 6)),
  tar_target(brain_sim_DEG_10_CELLS_5000_unbalanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                            perc.dyn.genes = 0.1,
                                                                            n.cells = 5000,
                                                                            perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                            n.subjects = 6)),
  tar_target(brain_sim_DEG_20_CELLS_5000_unbalanced, simulate_multi_subject(ref.dataset = brain_data_clean,
                                                                            perc.dyn.genes = 0.2,
                                                                            n.cells = 5000,
                                                                            perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                            n.subjects = 6)), 
  
  ##### PANCREAS #####
  # reference data 
  tar_target(panc_data_clean, fetch_baron_pancreas_data()), 
  ### SINGLE-SUBJECT 
  # 100 cells
  tar_target(panc_sim_DEG_01_CELLS_100, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                perc.dyn.genes = 0.01, 
                                                                n.cells = 100)),
  tar_target(panc_sim_DEG_05_CELLS_100, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                perc.dyn.genes = 0.05, 
                                                                n.cells = 100)),
  tar_target(panc_sim_DEG_10_CELLS_100, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                perc.dyn.genes = 0.10, 
                                                                n.cells = 100)),
  tar_target(panc_sim_DEG_20_CELLS_100, simulate_single_subject(ref.dataset = panc_data_clean,
                                                                perc.dyn.genes = 0.20, 
                                                                n.cells = 100)),
  # 500 cells
  tar_target(panc_sim_DEG_01_CELLS_500, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                perc.dyn.genes = 0.01, 
                                                                n.cells = 500)),
  tar_target(panc_sim_DEG_05_CELLS_500, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                perc.dyn.genes = 0.05, 
                                                                n.cells = 500)),
  tar_target(panc_sim_DEG_10_CELLS_500, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                perc.dyn.genes = 0.10, 
                                                                n.cells = 500)),
  tar_target(panc_sim_DEG_20_CELLS_500, simulate_single_subject(ref.dataset = panc_data_clean,
                                                                perc.dyn.genes = 0.20, 
                                                                n.cells = 500)),
  # 1000 cells
  tar_target(panc_sim_DEG_01_CELLS_1000, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.01, 
                                                                 n.cells = 1000)),
  tar_target(panc_sim_DEG_05_CELLS_1000, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.05, 
                                                                 n.cells = 1000)),
  tar_target(panc_sim_DEG_10_CELLS_1000, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.10, 
                                                                 n.cells = 1000)),
  tar_target(panc_sim_DEG_20_CELLS_1000, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.20, 
                                                                 n.cells = 1000)),
  # 2500 cells
  tar_target(panc_sim_DEG_01_CELLS_2500, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.01, 
                                                                 n.cells = 2500)),
  tar_target(panc_sim_DEG_05_CELLS_2500, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.05, 
                                                                 n.cells = 2500)),
  tar_target(panc_sim_DEG_10_CELLS_2500, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.10, 
                                                                 n.cells = 2500)),
  tar_target(panc_sim_DEG_20_CELLS_2500, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.20, 
                                                                 n.cells = 2500)),
  # 5000 cells
  tar_target(panc_sim_DEG_01_CELLS_5000, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.01, 
                                                                 n.cells = 5000)),
  tar_target(panc_sim_DEG_05_CELLS_5000, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.05, 
                                                                 n.cells = 5000)),
  tar_target(panc_sim_DEG_10_CELLS_5000, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.10, 
                                                                 n.cells = 5000)),
  tar_target(panc_sim_DEG_20_CELLS_5000, simulate_single_subject(ref.dataset = panc_data_clean, 
                                                                 perc.dyn.genes = 0.20, 
                                                                 n.cells = 5000)), 
  ### MULTI-SUBJECT -- homogeneous
  # 100 cells
  tar_target(panc_sim_DEG_10_CELLS_100_balanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                        perc.dyn.genes = 0.1,
                                                                        n.cells = 100,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(panc_sim_DEG_20_CELLS_100_balanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                        perc.dyn.genes = 0.2,
                                                                        n.cells = 100,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(panc_sim_DEG_10_CELLS_100_unbalanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                          perc.dyn.genes = 0.1,
                                                                          n.cells = 100,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  tar_target(panc_sim_DEG_20_CELLS_100_unbalanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                          perc.dyn.genes = 0.2,
                                                                          n.cells = 100,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  # 500 cells
  tar_target(panc_sim_DEG_10_CELLS_500_balanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                        perc.dyn.genes = 0.1,
                                                                        n.cells = 500,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(panc_sim_DEG_20_CELLS_500_balanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                        perc.dyn.genes = 0.2,
                                                                        n.cells = 500,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(panc_sim_DEG_10_CELLS_500_unbalanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                          perc.dyn.genes = 0.1,
                                                                          n.cells = 500,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  tar_target(panc_sim_DEG_20_CELLS_500_unbalanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                          perc.dyn.genes = 0.2,
                                                                          n.cells = 500,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  # 1000 cells
  tar_target(panc_sim_DEG_10_CELLS_1000_balanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                         perc.dyn.genes = 0.1,
                                                                         n.cells = 1000,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(panc_sim_DEG_20_CELLS_1000_balanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                         perc.dyn.genes = 0.2,
                                                                         n.cells = 1000,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(panc_sim_DEG_10_CELLS_1000_unbalanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                           perc.dyn.genes = 0.1,
                                                                           n.cells = 1000,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  tar_target(panc_sim_DEG_20_CELLS_1000_unbalanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                           perc.dyn.genes = 0.2,
                                                                           n.cells = 1000,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  # 2500 cells
  tar_target(panc_sim_DEG_10_CELLS_2500_balanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                         perc.dyn.genes = 0.1,
                                                                         n.cells = 2500,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(panc_sim_DEG_20_CELLS_2500_balanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                         perc.dyn.genes = 0.2,
                                                                         n.cells = 2500,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(panc_sim_DEG_10_CELLS_2500_unbalanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                           perc.dyn.genes = 0.1,
                                                                           n.cells = 2500,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  tar_target(panc_sim_DEG_20_CELLS_2500_unbalanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                           perc.dyn.genes = 0.2,
                                                                           n.cells = 2500,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  # 5000 cells
  tar_target(panc_sim_DEG_10_CELLS_5000_balanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                         perc.dyn.genes = 0.1,
                                                                         n.cells = 5000,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(panc_sim_DEG_20_CELLS_5000_balanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                         perc.dyn.genes = 0.2,
                                                                         n.cells = 5000,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(panc_sim_DEG_10_CELLS_5000_unbalanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                           perc.dyn.genes = 0.1,
                                                                           n.cells = 5000,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  tar_target(panc_sim_DEG_20_CELLS_5000_unbalanced, simulate_multi_subject(ref.dataset = panc_data_clean,
                                                                           perc.dyn.genes = 0.2,
                                                                           n.cells = 5000,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)), 
  
  ##### ENDOCRINOGENESIS #####
  # reference data 
  tar_target(endo_data_clean, fetch_bastidas_ponce_pancreas_data()), 
  ### SINGLE-SUBJECT 
  # 100 cells
  tar_target(endo_sim_DEG_01_CELLS_100, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                perc.dyn.genes = 0.01, 
                                                                n.cells = 100)),
  tar_target(endo_sim_DEG_05_CELLS_100, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                perc.dyn.genes = 0.05, 
                                                                n.cells = 100)),
  tar_target(endo_sim_DEG_10_CELLS_100, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                perc.dyn.genes = 0.10, 
                                                                n.cells = 100)),
  tar_target(endo_sim_DEG_20_CELLS_100, simulate_single_subject(ref.dataset = endo_data_clean,
                                                                perc.dyn.genes = 0.20, 
                                                                n.cells = 100)),
  # 500 cells
  tar_target(endo_sim_DEG_01_CELLS_500, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                perc.dyn.genes = 0.01, 
                                                                n.cells = 500)),
  tar_target(endo_sim_DEG_05_CELLS_500, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                perc.dyn.genes = 0.05, 
                                                                n.cells = 500)),
  tar_target(endo_sim_DEG_10_CELLS_500, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                perc.dyn.genes = 0.10, 
                                                                n.cells = 500)),
  tar_target(endo_sim_DEG_20_CELLS_500, simulate_single_subject(ref.dataset = endo_data_clean,
                                                                perc.dyn.genes = 0.20, 
                                                                n.cells = 500)),
  # 1000 cells
  tar_target(endo_sim_DEG_01_CELLS_1000, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.01, 
                                                                 n.cells = 1000)),
  tar_target(endo_sim_DEG_05_CELLS_1000, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.05, 
                                                                 n.cells = 1000)),
  tar_target(endo_sim_DEG_10_CELLS_1000, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.10, 
                                                                 n.cells = 1000)),
  tar_target(endo_sim_DEG_20_CELLS_1000, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.20, 
                                                                 n.cells = 1000)),
  # 2500 cells
  tar_target(endo_sim_DEG_01_CELLS_2500, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.01, 
                                                                 n.cells = 2500)),
  tar_target(endo_sim_DEG_05_CELLS_2500, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.05, 
                                                                 n.cells = 2500)),
  tar_target(endo_sim_DEG_10_CELLS_2500, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.10, 
                                                                 n.cells = 2500)),
  tar_target(endo_sim_DEG_20_CELLS_2500, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.20, 
                                                                 n.cells = 2500)),
  # 5000 cells
  tar_target(endo_sim_DEG_01_CELLS_5000, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.01, 
                                                                 n.cells = 5000)),
  tar_target(endo_sim_DEG_05_CELLS_5000, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.05, 
                                                                 n.cells = 5000)),
  tar_target(endo_sim_DEG_10_CELLS_5000, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.10, 
                                                                 n.cells = 5000)),
  tar_target(endo_sim_DEG_20_CELLS_5000, simulate_single_subject(ref.dataset = endo_data_clean, 
                                                                 perc.dyn.genes = 0.20, 
                                                                 n.cells = 5000)), 
  ### MULTI-SUBJECT -- homogeneous
  # 100 cells
  tar_target(endo_sim_DEG_10_CELLS_100_balanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                        perc.dyn.genes = 0.1,
                                                                        n.cells = 100,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(endo_sim_DEG_20_CELLS_100_balanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                        perc.dyn.genes = 0.2,
                                                                        n.cells = 100,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(endo_sim_DEG_10_CELLS_100_unbalanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                          perc.dyn.genes = 0.1,
                                                                          n.cells = 100,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  tar_target(endo_sim_DEG_20_CELLS_100_unbalanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                          perc.dyn.genes = 0.2,
                                                                          n.cells = 100,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  # 500 cells
  tar_target(endo_sim_DEG_10_CELLS_500_balanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                        perc.dyn.genes = 0.1,
                                                                        n.cells = 500,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(endo_sim_DEG_20_CELLS_500_balanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                        perc.dyn.genes = 0.2,
                                                                        n.cells = 500,
                                                                        perc.allocation = rep(1/6, 6),
                                                                        n.subjects = 6)),
  tar_target(endo_sim_DEG_10_CELLS_500_unbalanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                          perc.dyn.genes = 0.1,
                                                                          n.cells = 500,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  tar_target(endo_sim_DEG_20_CELLS_500_unbalanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                          perc.dyn.genes = 0.2,
                                                                          n.cells = 500,
                                                                          perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                          n.subjects = 6)),
  # 1000 cells
  tar_target(endo_sim_DEG_10_CELLS_1000_balanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                         perc.dyn.genes = 0.1,
                                                                         n.cells = 1000,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(endo_sim_DEG_20_CELLS_1000_balanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                         perc.dyn.genes = 0.2,
                                                                         n.cells = 1000,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(endo_sim_DEG_10_CELLS_1000_unbalanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                           perc.dyn.genes = 0.1,
                                                                           n.cells = 1000,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  tar_target(endo_sim_DEG_20_CELLS_1000_unbalanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                           perc.dyn.genes = 0.2,
                                                                           n.cells = 1000,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  # 2500 cells
  tar_target(endo_sim_DEG_10_CELLS_2500_balanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                         perc.dyn.genes = 0.1,
                                                                         n.cells = 2500,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(endo_sim_DEG_20_CELLS_2500_balanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                         perc.dyn.genes = 0.2,
                                                                         n.cells = 2500,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(endo_sim_DEG_10_CELLS_2500_unbalanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                           perc.dyn.genes = 0.1,
                                                                           n.cells = 2500,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  tar_target(endo_sim_DEG_20_CELLS_2500_unbalanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                           perc.dyn.genes = 0.2,
                                                                           n.cells = 2500,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  # 5000 cells
  tar_target(endo_sim_DEG_10_CELLS_5000_balanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                         perc.dyn.genes = 0.1,
                                                                         n.cells = 5000,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(endo_sim_DEG_20_CELLS_5000_balanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                         perc.dyn.genes = 0.2,
                                                                         n.cells = 5000,
                                                                         perc.allocation = rep(1/6, 6),
                                                                         n.subjects = 6)),
  tar_target(endo_sim_DEG_10_CELLS_5000_unbalanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                           perc.dyn.genes = 0.1,
                                                                           n.cells = 5000,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)),
  tar_target(endo_sim_DEG_20_CELLS_5000_unbalanced, simulate_multi_subject(ref.dataset = endo_data_clean,
                                                                           perc.dyn.genes = 0.2,
                                                                           n.cells = 5000,
                                                                           perc.allocation = c(0.25, 0.15, 0.2, 0.2, 0.1, 0.1),
                                                                           n.subjects = 6)), 
  
  ##### QC
  tar_render(QC_report, "Reports/Simulation_QC.Rmd")
)
