##### setup #####

library(future)
library(targets)
library(tarchetypes)
library(future.callr)

future::plan(future.callr::callr)
options(future.globals.maxSize = 100000 * 1024^2)  # 100GB max size -- necessary for loading in all sim datasets

source("./R/functions_scLANE_GLM.R")

tar_option_set(packages = c("qs", 
                            "glm2", 
                            "geeM", 
                            "mgcv", 
                            "pryr", 
                            "MASS", 
                            "tidyr", 
                            "stats", 
                            "broom", 
                            "scran", 
                            "gamlss", 
                            "igraph",
                            "scater", 
                            "scLANE", 
                            "foreach",  
                            "scRNAseq", 
                            "parallel", 
                            "bigstatsr", 
                            "S4Vectors", 
                            "tidyverse", 
                            "doParallel", 
                            "SummarizedExperiment", 
                            "SingleCellExperiment"), 
               imports = c("scLANE"), 
               error = "continue", 
               memory = "transient",
               retrieval = "worker", 
               storage = "worker", 
               garbage_collection = TRUE, 
               format = "qs")

# targets 
list(
  ##### UPSTREAM TARGETS #####
  ##### BRAIN #####
  ### FILES ###
  # 100 cells
  tar_target(brain_sim_DEG_10_CELLS_100_balanced_file, "store_simulation/objects/brain_sim_DEG_10_CELLS_100_balanced", format = "file"),
  tar_target(brain_sim_DEG_20_CELLS_100_balanced_file, "store_simulation/objects/brain_sim_DEG_20_CELLS_100_balanced", format = "file"),
  tar_target(brain_sim_DEG_10_CELLS_100_unbalanced_file, "store_simulation/objects/brain_sim_DEG_10_CELLS_100_unbalanced", format = "file"),
  tar_target(brain_sim_DEG_20_CELLS_100_unbalanced_file, "store_simulation/objects/brain_sim_DEG_20_CELLS_100_unbalanced", format = "file"),
  # 500 cells
  tar_target(brain_sim_DEG_10_CELLS_500_balanced_file, "store_simulation/objects/brain_sim_DEG_10_CELLS_500_balanced", format = "file"),
  tar_target(brain_sim_DEG_20_CELLS_500_balanced_file, "store_simulation/objects/brain_sim_DEG_20_CELLS_500_balanced", format = "file"),
  tar_target(brain_sim_DEG_10_CELLS_500_unbalanced_file, "store_simulation/objects/brain_sim_DEG_10_CELLS_500_unbalanced", format = "file"),
  tar_target(brain_sim_DEG_20_CELLS_500_unbalanced_file, "store_simulation/objects/brain_sim_DEG_20_CELLS_500_unbalanced", format = "file"),
  # 1000 cells
  tar_target(brain_sim_DEG_10_CELLS_1000_balanced_file, "store_simulation/objects/brain_sim_DEG_10_CELLS_1000_balanced", format = "file"),
  tar_target(brain_sim_DEG_20_CELLS_1000_balanced_file, "store_simulation/objects/brain_sim_DEG_20_CELLS_1000_balanced", format = "file"),
  tar_target(brain_sim_DEG_10_CELLS_1000_unbalanced_file, "store_simulation/objects/brain_sim_DEG_10_CELLS_1000_unbalanced", format = "file"),
  tar_target(brain_sim_DEG_20_CELLS_1000_unbalanced_file, "store_simulation/objects/brain_sim_DEG_20_CELLS_1000_unbalanced", format = "file"),
  # 2500 cells
  tar_target(brain_sim_DEG_10_CELLS_2500_balanced_file, "store_simulation/objects/brain_sim_DEG_10_CELLS_2500_balanced", format = "file"),
  tar_target(brain_sim_DEG_20_CELLS_2500_balanced_file, "store_simulation/objects/brain_sim_DEG_20_CELLS_2500_balanced", format = "file"),
  tar_target(brain_sim_DEG_10_CELLS_2500_unbalanced_file, "store_simulation/objects/brain_sim_DEG_10_CELLS_2500_unbalanced", format = "file"),
  tar_target(brain_sim_DEG_20_CELLS_2500_unbalanced_file, "store_simulation/objects/brain_sim_DEG_20_CELLS_2500_unbalanced", format = "file"),
  # 5000 cells
  tar_target(brain_sim_DEG_10_CELLS_5000_balanced_file, "store_simulation/objects/brain_sim_DEG_10_CELLS_5000_balanced", format = "file"),
  tar_target(brain_sim_DEG_20_CELLS_5000_balanced_file, "store_simulation/objects/brain_sim_DEG_20_CELLS_5000_balanced", format = "file"),
  tar_target(brain_sim_DEG_10_CELLS_5000_unbalanced_file, "store_simulation/objects/brain_sim_DEG_10_CELLS_5000_unbalanced", format = "file"),
  tar_target(brain_sim_DEG_20_CELLS_5000_unbalanced_file, "store_simulation/objects/brain_sim_DEG_20_CELLS_5000_unbalanced", format = "file"),
  
  ### OBJECTS ###
  # 100 cells 
  tar_target(brain_sim_DEG_10_CELLS_100_balanced, qs::qread(brain_sim_DEG_10_CELLS_100_balanced_file)), 
  tar_target(brain_sim_DEG_20_CELLS_100_balanced, qs::qread(brain_sim_DEG_20_CELLS_100_balanced_file)), 
  tar_target(brain_sim_DEG_10_CELLS_100_unbalanced, qs::qread(brain_sim_DEG_10_CELLS_100_unbalanced_file)), 
  tar_target(brain_sim_DEG_20_CELLS_100_unbalanced, qs::qread(brain_sim_DEG_20_CELLS_100_unbalanced_file)), 
  # 500 cells 
  tar_target(brain_sim_DEG_10_CELLS_500_balanced, qs::qread(brain_sim_DEG_10_CELLS_500_balanced_file)), 
  tar_target(brain_sim_DEG_20_CELLS_500_balanced, qs::qread(brain_sim_DEG_20_CELLS_500_balanced_file)), 
  tar_target(brain_sim_DEG_10_CELLS_500_unbalanced, qs::qread(brain_sim_DEG_10_CELLS_500_unbalanced_file)), 
  tar_target(brain_sim_DEG_20_CELLS_500_unbalanced, qs::qread(brain_sim_DEG_20_CELLS_500_unbalanced_file)), 
  # 1000 cells 
  tar_target(brain_sim_DEG_10_CELLS_1000_balanced, qs::qread(brain_sim_DEG_10_CELLS_1000_balanced_file)), 
  tar_target(brain_sim_DEG_20_CELLS_1000_balanced, qs::qread(brain_sim_DEG_20_CELLS_1000_balanced_file)), 
  tar_target(brain_sim_DEG_10_CELLS_1000_unbalanced, qs::qread(brain_sim_DEG_10_CELLS_1000_unbalanced_file)), 
  tar_target(brain_sim_DEG_20_CELLS_1000_unbalanced, qs::qread(brain_sim_DEG_20_CELLS_1000_unbalanced_file)), 
  # 2500 cells
  tar_target(brain_sim_DEG_10_CELLS_2500_balanced, qs::qread(brain_sim_DEG_10_CELLS_2500_balanced_file)), 
  tar_target(brain_sim_DEG_20_CELLS_2500_balanced, qs::qread(brain_sim_DEG_20_CELLS_2500_balanced_file)), 
  tar_target(brain_sim_DEG_10_CELLS_2500_unbalanced, qs::qread(brain_sim_DEG_10_CELLS_2500_unbalanced_file)), 
  tar_target(brain_sim_DEG_20_CELLS_2500_unbalanced, qs::qread(brain_sim_DEG_20_CELLS_2500_unbalanced_file)), 
  # 5000 cells 
  tar_target(brain_sim_DEG_10_CELLS_5000_balanced, qs::qread(brain_sim_DEG_10_CELLS_5000_balanced_file)), 
  tar_target(brain_sim_DEG_20_CELLS_5000_balanced, qs::qread(brain_sim_DEG_20_CELLS_5000_balanced_file)), 
  tar_target(brain_sim_DEG_10_CELLS_5000_unbalanced, qs::qread(brain_sim_DEG_10_CELLS_5000_unbalanced_file)), 
  tar_target(brain_sim_DEG_20_CELLS_5000_unbalanced, qs::qread(brain_sim_DEG_20_CELLS_5000_unbalanced_file)), 
  
  ##### PANCREAS #####
  ### FILES ###
  # 100 cells
  tar_target(panc_sim_DEG_10_CELLS_100_balanced_file, "store_simulation/objects/panc_sim_DEG_10_CELLS_100_balanced", format = "file"),
  tar_target(panc_sim_DEG_20_CELLS_100_balanced_file, "store_simulation/objects/panc_sim_DEG_20_CELLS_100_balanced", format = "file"),
  tar_target(panc_sim_DEG_10_CELLS_100_unbalanced_file, "store_simulation/objects/panc_sim_DEG_10_CELLS_100_unbalanced", format = "file"),
  tar_target(panc_sim_DEG_20_CELLS_100_unbalanced_file, "store_simulation/objects/panc_sim_DEG_20_CELLS_100_unbalanced", format = "file"),
  # 500 cells
  tar_target(panc_sim_DEG_10_CELLS_500_balanced_file, "store_simulation/objects/panc_sim_DEG_10_CELLS_500_balanced", format = "file"),
  tar_target(panc_sim_DEG_20_CELLS_500_balanced_file, "store_simulation/objects/panc_sim_DEG_20_CELLS_500_balanced", format = "file"),
  tar_target(panc_sim_DEG_10_CELLS_500_unbalanced_file, "store_simulation/objects/panc_sim_DEG_10_CELLS_500_unbalanced", format = "file"),
  tar_target(panc_sim_DEG_20_CELLS_500_unbalanced_file, "store_simulation/objects/panc_sim_DEG_20_CELLS_500_unbalanced", format = "file"),
  # 1000 cells
  tar_target(panc_sim_DEG_10_CELLS_1000_balanced_file, "store_simulation/objects/panc_sim_DEG_10_CELLS_1000_balanced", format = "file"),
  tar_target(panc_sim_DEG_20_CELLS_1000_balanced_file, "store_simulation/objects/panc_sim_DEG_20_CELLS_1000_balanced", format = "file"),
  tar_target(panc_sim_DEG_10_CELLS_1000_unbalanced_file, "store_simulation/objects/panc_sim_DEG_10_CELLS_1000_unbalanced", format = "file"),
  tar_target(panc_sim_DEG_20_CELLS_1000_unbalanced_file, "store_simulation/objects/panc_sim_DEG_20_CELLS_1000_unbalanced", format = "file"),
  # 2500 cells
  tar_target(panc_sim_DEG_10_CELLS_2500_balanced_file, "store_simulation/objects/panc_sim_DEG_10_CELLS_2500_balanced", format = "file"),
  tar_target(panc_sim_DEG_20_CELLS_2500_balanced_file, "store_simulation/objects/panc_sim_DEG_20_CELLS_2500_balanced", format = "file"),
  tar_target(panc_sim_DEG_10_CELLS_2500_unbalanced_file, "store_simulation/objects/panc_sim_DEG_10_CELLS_2500_unbalanced", format = "file"),
  tar_target(panc_sim_DEG_20_CELLS_2500_unbalanced_file, "store_simulation/objects/panc_sim_DEG_20_CELLS_2500_unbalanced", format = "file"),
  # 5000 cells
  tar_target(panc_sim_DEG_10_CELLS_5000_balanced_file, "store_simulation/objects/panc_sim_DEG_10_CELLS_5000_balanced", format = "file"),
  tar_target(panc_sim_DEG_20_CELLS_5000_balanced_file, "store_simulation/objects/panc_sim_DEG_20_CELLS_5000_balanced", format = "file"),
  tar_target(panc_sim_DEG_10_CELLS_5000_unbalanced_file, "store_simulation/objects/panc_sim_DEG_10_CELLS_5000_unbalanced", format = "file"),
  tar_target(panc_sim_DEG_20_CELLS_5000_unbalanced_file, "store_simulation/objects/panc_sim_DEG_20_CELLS_5000_unbalanced", format = "file"),
  
  ### OBJECTS ###
  # 100 cells 
  tar_target(panc_sim_DEG_10_CELLS_100_balanced, qs::qread(panc_sim_DEG_10_CELLS_100_balanced_file)), 
  tar_target(panc_sim_DEG_20_CELLS_100_balanced, qs::qread(panc_sim_DEG_20_CELLS_100_balanced_file)), 
  tar_target(panc_sim_DEG_10_CELLS_100_unbalanced, qs::qread(panc_sim_DEG_10_CELLS_100_unbalanced_file)), 
  tar_target(panc_sim_DEG_20_CELLS_100_unbalanced, qs::qread(panc_sim_DEG_20_CELLS_100_unbalanced_file)), 
  # 500 cells 
  tar_target(panc_sim_DEG_10_CELLS_500_balanced, qs::qread(panc_sim_DEG_10_CELLS_500_balanced_file)), 
  tar_target(panc_sim_DEG_20_CELLS_500_balanced, qs::qread(panc_sim_DEG_20_CELLS_500_balanced_file)), 
  tar_target(panc_sim_DEG_10_CELLS_500_unbalanced, qs::qread(panc_sim_DEG_10_CELLS_500_unbalanced_file)), 
  tar_target(panc_sim_DEG_20_CELLS_500_unbalanced, qs::qread(panc_sim_DEG_20_CELLS_500_unbalanced_file)), 
  # 1000 cells 
  tar_target(panc_sim_DEG_10_CELLS_1000_balanced, qs::qread(panc_sim_DEG_10_CELLS_1000_balanced_file)), 
  tar_target(panc_sim_DEG_20_CELLS_1000_balanced, qs::qread(panc_sim_DEG_20_CELLS_1000_balanced_file)), 
  tar_target(panc_sim_DEG_10_CELLS_1000_unbalanced, qs::qread(panc_sim_DEG_10_CELLS_1000_unbalanced_file)), 
  tar_target(panc_sim_DEG_20_CELLS_1000_unbalanced, qs::qread(panc_sim_DEG_20_CELLS_1000_unbalanced_file)), 
  # 2500 cells
  tar_target(panc_sim_DEG_10_CELLS_2500_balanced, qs::qread(panc_sim_DEG_10_CELLS_2500_balanced_file)), 
  tar_target(panc_sim_DEG_20_CELLS_2500_balanced, qs::qread(panc_sim_DEG_20_CELLS_2500_balanced_file)), 
  tar_target(panc_sim_DEG_10_CELLS_2500_unbalanced, qs::qread(panc_sim_DEG_10_CELLS_2500_unbalanced_file)), 
  tar_target(panc_sim_DEG_20_CELLS_2500_unbalanced, qs::qread(panc_sim_DEG_20_CELLS_2500_unbalanced_file)), 
  # 5000 cells 
  tar_target(panc_sim_DEG_10_CELLS_5000_balanced, qs::qread(panc_sim_DEG_10_CELLS_5000_balanced_file)), 
  tar_target(panc_sim_DEG_20_CELLS_5000_balanced, qs::qread(panc_sim_DEG_20_CELLS_5000_balanced_file)), 
  tar_target(panc_sim_DEG_10_CELLS_5000_unbalanced, qs::qread(panc_sim_DEG_10_CELLS_5000_unbalanced_file)), 
  tar_target(panc_sim_DEG_20_CELLS_5000_unbalanced, qs::qread(panc_sim_DEG_20_CELLS_5000_unbalanced_file)), 
  
  ##### ENDOCRINOGENESIS #####
  ### FILES ###
  # 100 cells
  tar_target(endo_sim_DEG_10_CELLS_100_balanced_file, "store_simulation/objects/endo_sim_DEG_10_CELLS_100_balanced", format = "file"),
  tar_target(endo_sim_DEG_20_CELLS_100_balanced_file, "store_simulation/objects/endo_sim_DEG_20_CELLS_100_balanced", format = "file"),
  tar_target(endo_sim_DEG_10_CELLS_100_unbalanced_file, "store_simulation/objects/endo_sim_DEG_10_CELLS_100_unbalanced", format = "file"),
  tar_target(endo_sim_DEG_20_CELLS_100_unbalanced_file, "store_simulation/objects/endo_sim_DEG_20_CELLS_100_unbalanced", format = "file"),
  # 500 cells
  tar_target(endo_sim_DEG_10_CELLS_500_balanced_file, "store_simulation/objects/endo_sim_DEG_10_CELLS_500_balanced", format = "file"),
  tar_target(endo_sim_DEG_20_CELLS_500_balanced_file, "store_simulation/objects/endo_sim_DEG_20_CELLS_500_balanced", format = "file"),
  tar_target(endo_sim_DEG_10_CELLS_500_unbalanced_file, "store_simulation/objects/endo_sim_DEG_10_CELLS_500_unbalanced", format = "file"),
  tar_target(endo_sim_DEG_20_CELLS_500_unbalanced_file, "store_simulation/objects/endo_sim_DEG_20_CELLS_500_unbalanced", format = "file"),
  # 1000 cells
  tar_target(endo_sim_DEG_10_CELLS_1000_balanced_file, "store_simulation/objects/endo_sim_DEG_10_CELLS_1000_balanced", format = "file"),
  tar_target(endo_sim_DEG_20_CELLS_1000_balanced_file, "store_simulation/objects/endo_sim_DEG_20_CELLS_1000_balanced", format = "file"),
  tar_target(endo_sim_DEG_10_CELLS_1000_unbalanced_file, "store_simulation/objects/endo_sim_DEG_10_CELLS_1000_unbalanced", format = "file"),
  tar_target(endo_sim_DEG_20_CELLS_1000_unbalanced_file, "store_simulation/objects/endo_sim_DEG_20_CELLS_1000_unbalanced", format = "file"),
  # 2500 cells
  tar_target(endo_sim_DEG_10_CELLS_2500_balanced_file, "store_simulation/objects/endo_sim_DEG_10_CELLS_2500_balanced", format = "file"),
  tar_target(endo_sim_DEG_20_CELLS_2500_balanced_file, "store_simulation/objects/endo_sim_DEG_20_CELLS_2500_balanced", format = "file"),
  tar_target(endo_sim_DEG_10_CELLS_2500_unbalanced_file, "store_simulation/objects/endo_sim_DEG_10_CELLS_2500_unbalanced", format = "file"),
  tar_target(endo_sim_DEG_20_CELLS_2500_unbalanced_file, "store_simulation/objects/endo_sim_DEG_20_CELLS_2500_unbalanced", format = "file"),
  # 5000 cells
  tar_target(endo_sim_DEG_10_CELLS_5000_balanced_file, "store_simulation/objects/endo_sim_DEG_10_CELLS_5000_balanced", format = "file"),
  tar_target(endo_sim_DEG_20_CELLS_5000_balanced_file, "store_simulation/objects/endo_sim_DEG_20_CELLS_5000_balanced", format = "file"),
  tar_target(endo_sim_DEG_10_CELLS_5000_unbalanced_file, "store_simulation/objects/endo_sim_DEG_10_CELLS_5000_unbalanced", format = "file"),
  tar_target(endo_sim_DEG_20_CELLS_5000_unbalanced_file, "store_simulation/objects/endo_sim_DEG_20_CELLS_5000_unbalanced", format = "file"),
  
  ### OBJECTS ###
  # 100 cells 
  tar_target(endo_sim_DEG_10_CELLS_100_balanced, qs::qread(endo_sim_DEG_10_CELLS_100_balanced_file)), 
  tar_target(endo_sim_DEG_20_CELLS_100_balanced, qs::qread(endo_sim_DEG_20_CELLS_100_balanced_file)), 
  tar_target(endo_sim_DEG_10_CELLS_100_unbalanced, qs::qread(endo_sim_DEG_10_CELLS_100_unbalanced_file)), 
  tar_target(endo_sim_DEG_20_CELLS_100_unbalanced, qs::qread(endo_sim_DEG_20_CELLS_100_unbalanced_file)), 
  # 500 cells 
  tar_target(endo_sim_DEG_10_CELLS_500_balanced, qs::qread(endo_sim_DEG_10_CELLS_500_balanced_file)), 
  tar_target(endo_sim_DEG_20_CELLS_500_balanced, qs::qread(endo_sim_DEG_20_CELLS_500_balanced_file)), 
  tar_target(endo_sim_DEG_10_CELLS_500_unbalanced, qs::qread(endo_sim_DEG_10_CELLS_500_unbalanced_file)), 
  tar_target(endo_sim_DEG_20_CELLS_500_unbalanced, qs::qread(endo_sim_DEG_20_CELLS_500_unbalanced_file)), 
  # 1000 cells 
  tar_target(endo_sim_DEG_10_CELLS_1000_balanced, qs::qread(endo_sim_DEG_10_CELLS_1000_balanced_file)), 
  tar_target(endo_sim_DEG_20_CELLS_1000_balanced, qs::qread(endo_sim_DEG_20_CELLS_1000_balanced_file)), 
  tar_target(endo_sim_DEG_10_CELLS_1000_unbalanced, qs::qread(endo_sim_DEG_10_CELLS_1000_unbalanced_file)), 
  tar_target(endo_sim_DEG_20_CELLS_1000_unbalanced, qs::qread(endo_sim_DEG_20_CELLS_1000_unbalanced_file)), 
  # 2500 cells
  tar_target(endo_sim_DEG_10_CELLS_2500_balanced, qs::qread(endo_sim_DEG_10_CELLS_2500_balanced_file)), 
  tar_target(endo_sim_DEG_20_CELLS_2500_balanced, qs::qread(endo_sim_DEG_20_CELLS_2500_balanced_file)), 
  tar_target(endo_sim_DEG_10_CELLS_2500_unbalanced, qs::qread(endo_sim_DEG_10_CELLS_2500_unbalanced_file)), 
  tar_target(endo_sim_DEG_20_CELLS_2500_unbalanced, qs::qread(endo_sim_DEG_20_CELLS_2500_unbalanced_file)), 
  # 5000 cells 
  tar_target(endo_sim_DEG_10_CELLS_5000_balanced, qs::qread(endo_sim_DEG_10_CELLS_5000_balanced_file)), 
  tar_target(endo_sim_DEG_20_CELLS_5000_balanced, qs::qread(endo_sim_DEG_20_CELLS_5000_balanced_file)), 
  tar_target(endo_sim_DEG_10_CELLS_5000_unbalanced, qs::qread(endo_sim_DEG_10_CELLS_5000_unbalanced_file)), 
  tar_target(endo_sim_DEG_20_CELLS_5000_unbalanced, qs::qread(endo_sim_DEG_20_CELLS_5000_unbalanced_file)), 
  
  ##### MODELS #####
  ##### BRAIN #####
  ### MULTI-SUBJECT
  # 100 cells
  tar_target(scLANE_GLM_brain_DEG_10_CELLS_100_balanced, run_scLANE_GLM(sim.data = brain_sim_DEG_10_CELLS_100_balanced, 
                                                                        n.genes.sample = 2200, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.10, Cells = 100, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_20_CELLS_100_balanced, run_scLANE_GLM(sim.data = brain_sim_DEG_20_CELLS_100_balanced, 
                                                                        n.genes.sample = 1000, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.20, Cells = 100, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_10_CELLS_100_unbalanced, run_scLANE_GLM(sim.data = brain_sim_DEG_10_CELLS_100_unbalanced,
                                                                          n.genes.sample = 1600, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.10, Cells = 100, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_20_CELLS_100_unbalanced, run_scLANE_GLM(sim.data = brain_sim_DEG_20_CELLS_100_unbalanced,
                                                                          n.genes.sample = 3100, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.20, Cells = 100, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  # 500 cells
  tar_target(scLANE_GLM_brain_DEG_10_CELLS_500_balanced, run_scLANE_GLM(sim.data = brain_sim_DEG_10_CELLS_500_balanced, 
                                                                        n.genes.sample = 2200, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.10, Cells = 500, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_20_CELLS_500_balanced, run_scLANE_GLM(sim.data = brain_sim_DEG_20_CELLS_500_balanced, 
                                                                        n.genes.sample = 1000, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.20, Cells = 500, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_10_CELLS_500_unbalanced, run_scLANE_GLM(sim.data = brain_sim_DEG_10_CELLS_500_unbalanced,
                                                                          n.genes.sample = 1600, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.10, Cells = 500, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_20_CELLS_500_unbalanced, run_scLANE_GLM(sim.data = brain_sim_DEG_20_CELLS_500_unbalanced,
                                                                          n.genes.sample = 3100, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.20, Cells = 500, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  # 1000 cells
  tar_target(scLANE_GLM_brain_DEG_10_CELLS_1000_balanced, run_scLANE_GLM(sim.data = brain_sim_DEG_10_CELLS_1000_balanced, 
                                                                         n.genes.sample = 1200, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.10, Cells = 1000, Allocation = "Balanced", Method = "GLM"),
                                                                         n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_20_CELLS_1000_balanced, run_scLANE_GLM(sim.data = brain_sim_DEG_20_CELLS_1000_balanced, 
                                                                         n.genes.sample = 1400, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.20, Cells = 1000, Allocation = "Balanced", Method = "GLM"),
                                                                         n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_10_CELLS_1000_unbalanced, run_scLANE_GLM(sim.data = brain_sim_DEG_10_CELLS_1000_unbalanced,
                                                                           n.genes.sample = 2500, 
                                                                           param.list = list(Prop_Dyn_Genes = 0.10, Cells = 1000, Allocation = "Unbalanced", Method = "GLM"),
                                                                           n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_20_CELLS_1000_unbalanced, run_scLANE_GLM(sim.data = brain_sim_DEG_20_CELLS_1000_unbalanced,
                                                                           n.genes.sample = 1800, 
                                                                           param.list = list(Prop_Dyn_Genes = 0.20, Cells = 1000, Allocation = "Unbalanced", Method = "GLM"),
                                                                           n.cores = 4)),
  # 2500 cells
  tar_target(scLANE_GLM_brain_DEG_10_CELLS_2500_balanced, run_scLANE_GLM(sim.data = brain_sim_DEG_10_CELLS_2500_balanced, 
                                                                         n.genes.sample = 2600, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.10, Cells = 2500, Allocation = "Balanced", Method = "GLM"),
                                                                         n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_20_CELLS_2500_balanced, run_scLANE_GLM(sim.data = brain_sim_DEG_20_CELLS_2500_balanced, 
                                                                         n.genes.sample = 2900, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.20, Cells = 2500, Allocation = "Balanced", Method = "GLM"),
                                                                         n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_10_CELLS_2500_unbalanced, run_scLANE_GLM(sim.data = brain_sim_DEG_10_CELLS_2500_unbalanced,
                                                                           n.genes.sample = 2200, 
                                                                           param.list = list(Prop_Dyn_Genes = 0.10, Cells = 2500, Allocation = "Unbalanced", Method = "GLM"),
                                                                           n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_20_CELLS_2500_unbalanced, run_scLANE_GLM(sim.data = brain_sim_DEG_20_CELLS_2500_unbalanced,
                                                                           n.genes.sample = 1700, 
                                                                           param.list = list(Prop_Dyn_Genes = 0.20, Cells = 2500, Allocation = "Unbalanced", Method = "GLM"),
                                                                           n.cores = 4)),
  # 5000 cells
  tar_target(scLANE_GLM_brain_DEG_10_CELLS_5000_balanced, run_scLANE_GLM(sim.data = brain_sim_DEG_10_CELLS_5000_balanced, 
                                                                         n.genes.sample = 3200, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.10, Cells = 5000, Allocation = "Balanced", Method = "GLM"),
                                                                         n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_20_CELLS_5000_balanced, run_scLANE_GLM(sim.data = brain_sim_DEG_20_CELLS_5000_balanced, 
                                                                         n.genes.sample = 1400, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.20, Cells = 5000, Allocation = "Balanced", Method = "GLM"),
                                                                         n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_10_CELLS_5000_unbalanced, run_scLANE_GLM(sim.data = brain_sim_DEG_10_CELLS_5000_unbalanced,
                                                                           n.genes.sample = 1600, 
                                                                           param.list = list(Prop_Dyn_Genes = 0.10, Cells = 5000, Allocation = "Unbalanced", Method = "GLM"),
                                                                           n.cores = 4)),
  tar_target(scLANE_GLM_brain_DEG_20_CELLS_5000_unbalanced, run_scLANE_GLM(sim.data = brain_sim_DEG_20_CELLS_5000_unbalanced,
                                                                           n.genes.sample = 2500, 
                                                                           param.list = list(Prop_Dyn_Genes = 0.20, Cells = 5000, Allocation = "Unbalanced", Method = "GLM"),
                                                                           n.cores = 4)),
  
  ##### PANCREAS #####
  ### MULTI-SUBJECT
  # 100 cells
  tar_target(scLANE_GLM_panc_DEG_10_CELLS_100_balanced, run_scLANE_GLM(sim.data = panc_sim_DEG_10_CELLS_100_balanced, 
                                                                       n.genes.sample = 2000, 
                                                                       param.list = list(Prop_Dyn_Genes = 0.10, Cells = 100, Allocation = "Balanced", Method = "GLM"),
                                                                       n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_20_CELLS_100_balanced, run_scLANE_GLM(sim.data = panc_sim_DEG_20_CELLS_100_balanced, 
                                                                       n.genes.sample = 2400, 
                                                                       param.list = list(Prop_Dyn_Genes = 0.20, Cells = 100, Allocation = "Balanced", Method = "GLM"),
                                                                       n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_10_CELLS_100_unbalanced, run_scLANE_GLM(sim.data = panc_sim_DEG_10_CELLS_100_unbalanced,
                                                                         n.genes.sample = 2100, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.10, Cells = 100, Allocation = "Unbalanced", Method = "GLM"),
                                                                         n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_20_CELLS_100_unbalanced, run_scLANE_GLM(sim.data = panc_sim_DEG_20_CELLS_100_unbalanced,
                                                                         n.genes.sample = 1300, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.20, Cells = 100, Allocation = "Unbalanced", Method = "GLM"),
                                                                         n.cores = 4)),
  # 500 cells
  tar_target(scLANE_GLM_panc_DEG_10_CELLS_500_balanced, run_scLANE_GLM(sim.data = panc_sim_DEG_10_CELLS_500_balanced, 
                                                                       n.genes.sample = 1800, 
                                                                       param.list = list(Prop_Dyn_Genes = 0.10, Cells = 500, Allocation = "Balanced", Method = "GLM"),
                                                                       n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_20_CELLS_500_balanced, run_scLANE_GLM(sim.data = panc_sim_DEG_20_CELLS_500_balanced, 
                                                                       n.genes.sample = 1700, 
                                                                       param.list = list(Prop_Dyn_Genes = 0.20, Cells = 500, Allocation = "Balanced", Method = "GLM"),
                                                                       n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_10_CELLS_500_unbalanced, run_scLANE_GLM(sim.data = panc_sim_DEG_10_CELLS_500_unbalanced,
                                                                         n.genes.sample = 2500, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.10, Cells = 500, Allocation = "Unbalanced", Method = "GLM"),
                                                                         n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_20_CELLS_500_unbalanced, run_scLANE_GLM(sim.data = panc_sim_DEG_20_CELLS_500_unbalanced,
                                                                         n.genes.sample = 2100, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.20, Cells = 500, Allocation = "Unbalanced", Method = "GLM"),
                                                                         n.cores = 4)),
  # 1000 cells
  tar_target(scLANE_GLM_panc_DEG_10_CELLS_1000_balanced, run_scLANE_GLM(sim.data = panc_sim_DEG_10_CELLS_1000_balanced, 
                                                                        n.genes.sample = 1800, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.10, Cells = 1000, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_20_CELLS_1000_balanced, run_scLANE_GLM(sim.data = panc_sim_DEG_20_CELLS_1000_balanced, 
                                                                        n.genes.sample = 1200, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.20, Cells = 1000, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_10_CELLS_1000_unbalanced, run_scLANE_GLM(sim.data = panc_sim_DEG_10_CELLS_1000_unbalanced,
                                                                          n.genes.sample = 2300, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.10, Cells = 1000, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_20_CELLS_1000_unbalanced, run_scLANE_GLM(sim.data = panc_sim_DEG_20_CELLS_1000_unbalanced,
                                                                          n.genes.sample = 3000, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.20, Cells = 1000, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  # 2500 cells
  tar_target(scLANE_GLM_panc_DEG_10_CELLS_2500_balanced, run_scLANE_GLM(sim.data = panc_sim_DEG_10_CELLS_2500_balanced, 
                                                                        n.genes.sample = 2600, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.10, Cells = 2500, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_20_CELLS_2500_balanced, run_scLANE_GLM(sim.data = panc_sim_DEG_20_CELLS_2500_balanced, 
                                                                        n.genes.sample = 2900, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.20, Cells = 2500, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_10_CELLS_2500_unbalanced, run_scLANE_GLM(sim.data = panc_sim_DEG_10_CELLS_2500_unbalanced,
                                                                          n.genes.sample = 2200, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.10, Cells = 2500, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_20_CELLS_2500_unbalanced, run_scLANE_GLM(sim.data = panc_sim_DEG_20_CELLS_2500_unbalanced,
                                                                          n.genes.sample = 1700, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.20, Cells = 2500, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  # 5000 cells
  tar_target(scLANE_GLM_panc_DEG_10_CELLS_5000_balanced, run_scLANE_GLM(sim.data = panc_sim_DEG_10_CELLS_5000_balanced, 
                                                                        n.genes.sample = 3000, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.10, Cells = 5000, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_20_CELLS_5000_balanced, run_scLANE_GLM(sim.data = panc_sim_DEG_20_CELLS_5000_balanced, 
                                                                        n.genes.sample = 2400, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.20, Cells = 5000, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_10_CELLS_5000_unbalanced, run_scLANE_GLM(sim.data = panc_sim_DEG_10_CELLS_5000_unbalanced,
                                                                          n.genes.sample = 1100, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.10, Cells = 5000, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  tar_target(scLANE_GLM_panc_DEG_20_CELLS_5000_unbalanced, run_scLANE_GLM(sim.data = panc_sim_DEG_20_CELLS_5000_unbalanced,
                                                                          n.genes.sample = 1400, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.20, Cells = 5000, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)), 
  
  ##### ENDOCRINOGENESIS #####
  ### MULTI-SUBJECT
  # 100 cells
  tar_target(scLANE_GLM_endo_DEG_10_CELLS_100_balanced, run_scLANE_GLM(sim.data = endo_sim_DEG_10_CELLS_100_balanced, 
                                                                       n.genes.sample = 1800, 
                                                                       param.list = list(Prop_Dyn_Genes = 0.10, Cells = 100, Allocation = "Balanced", Method = "GLM"),
                                                                       n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_20_CELLS_100_balanced, run_scLANE_GLM(sim.data = endo_sim_DEG_20_CELLS_100_balanced, 
                                                                       n.genes.sample = 2400, 
                                                                       param.list = list(Prop_Dyn_Genes = 0.20, Cells = 100, Allocation = "Balanced", Method = "GLM"),
                                                                       n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_10_CELLS_100_unbalanced, run_scLANE_GLM(sim.data = endo_sim_DEG_10_CELLS_100_unbalanced,
                                                                         n.genes.sample = 2100, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.10, Cells = 100, Allocation = "Unbalanced", Method = "GLM"),
                                                                         n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_20_CELLS_100_unbalanced, run_scLANE_GLM(sim.data = endo_sim_DEG_20_CELLS_100_unbalanced,
                                                                         n.genes.sample = 2700, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.20, Cells = 100, Allocation = "Unbalanced", Method = "GLM"),
                                                                         n.cores = 4)),
  # 500 cells
  tar_target(scLANE_GLM_endo_DEG_10_CELLS_500_balanced, run_scLANE_GLM(sim.data = endo_sim_DEG_10_CELLS_500_balanced, 
                                                                       n.genes.sample = 1500, 
                                                                       param.list = list(Prop_Dyn_Genes = 0.10, Cells = 500, Allocation = "Balanced", Method = "GLM"),
                                                                       n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_20_CELLS_500_balanced, run_scLANE_GLM(sim.data = endo_sim_DEG_20_CELLS_500_balanced, 
                                                                       n.genes.sample = 1700, 
                                                                       param.list = list(Prop_Dyn_Genes = 0.20, Cells = 500, Allocation = "Balanced", Method = "GLM"),
                                                                       n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_10_CELLS_500_unbalanced, run_scLANE_GLM(sim.data = endo_sim_DEG_10_CELLS_500_unbalanced,
                                                                         n.genes.sample = 3200, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.10, Cells = 500, Allocation = "Unbalanced", Method = "GLM"),
                                                                         n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_20_CELLS_500_unbalanced, run_scLANE_GLM(sim.data = endo_sim_DEG_20_CELLS_500_unbalanced,
                                                                         n.genes.sample = 1900, 
                                                                         param.list = list(Prop_Dyn_Genes = 0.20, Cells = 500, Allocation = "Unbalanced", Method = "GLM"),
                                                                         n.cores = 4)),
  # 1000 cells
  tar_target(scLANE_GLM_endo_DEG_10_CELLS_1000_balanced, run_scLANE_GLM(sim.data = endo_sim_DEG_10_CELLS_1000_balanced, 
                                                                        n.genes.sample = 1300, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.10, Cells = 1000, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_20_CELLS_1000_balanced, run_scLANE_GLM(sim.data = endo_sim_DEG_20_CELLS_1000_balanced, 
                                                                        n.genes.sample = 1500, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.20, Cells = 1000, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_10_CELLS_1000_unbalanced, run_scLANE_GLM(sim.data = endo_sim_DEG_10_CELLS_1000_unbalanced,
                                                                          n.genes.sample = 2300, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.10, Cells = 1000, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_20_CELLS_1000_unbalanced, run_scLANE_GLM(sim.data = endo_sim_DEG_20_CELLS_1000_unbalanced,
                                                                          n.genes.sample = 2600, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.20, Cells = 1000, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  # 2500 cells
  tar_target(scLANE_GLM_endo_DEG_10_CELLS_2500_balanced, run_scLANE_GLM(sim.data = endo_sim_DEG_10_CELLS_2500_balanced, 
                                                                        n.genes.sample = 2600, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.10, Cells = 2500, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_20_CELLS_2500_balanced, run_scLANE_GLM(sim.data = endo_sim_DEG_20_CELLS_2500_balanced, 
                                                                        n.genes.sample = 1200, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.20, Cells = 2500, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_10_CELLS_2500_unbalanced, run_scLANE_GLM(sim.data = endo_sim_DEG_10_CELLS_2500_unbalanced,
                                                                          n.genes.sample = 1200, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.10, Cells = 2500, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_20_CELLS_2500_unbalanced, run_scLANE_GLM(sim.data = endo_sim_DEG_20_CELLS_2500_unbalanced,
                                                                          n.genes.sample = 1700, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.20, Cells = 2500, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  # 5000 cells
  tar_target(scLANE_GLM_endo_DEG_10_CELLS_5000_balanced, run_scLANE_GLM(sim.data = endo_sim_DEG_10_CELLS_5000_balanced, 
                                                                        n.genes.sample = 2600, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.10, Cells = 5000, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_20_CELLS_5000_balanced, run_scLANE_GLM(sim.data = endo_sim_DEG_20_CELLS_5000_balanced, 
                                                                        n.genes.sample = 2200, 
                                                                        param.list = list(Prop_Dyn_Genes = 0.20, Cells = 5000, Allocation = "Balanced", Method = "GLM"),
                                                                        n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_10_CELLS_5000_unbalanced, run_scLANE_GLM(sim.data = endo_sim_DEG_10_CELLS_5000_unbalanced,
                                                                          n.genes.sample = 3200, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.10, Cells = 5000, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)),
  tar_target(scLANE_GLM_endo_DEG_20_CELLS_5000_unbalanced, run_scLANE_GLM(sim.data = endo_sim_DEG_20_CELLS_5000_unbalanced,
                                                                          n.genes.sample = 1800, 
                                                                          param.list = list(Prop_Dyn_Genes = 0.20, Cells = 5000, Allocation = "Unbalanced", Method = "GLM"),
                                                                          n.cores = 4)), 
  
  ##### QC #####
  tar_render(QC_report, "Reports/Model_Results_scLANE_GLM_Multi.Rmd")
)